name: Deploy Main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Build Docker image
        run: |
          docker build -t iemarjay/screen3-backend .
          docker tag iemarjay/screen3-backend iemarjay/screen3-backend:$GITHUB_SHA
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push iemarjay/screen3-backend:$GITHUB_SHA
          docker push iemarjay/screen3-backend

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.VPS_IP }} >> ~/.ssh/known_hosts

      - name: SSH into VPS and deploy with Docker Compose
        run: |
          ssh root@${{ secrets.VPS_IP }} 'cd ~/screen3 && docker compose pull backend && docker compose up backend -d'
